; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32 @ 6.13.0
board = esp32-c3-devkitm-1
framework = espidf
; ESP32-C3 SuperMini: 2MB Flash；固件 >1MB，PlatformIO 体积检查读此分区表
board_build.flash_size = 2MB
# board_upload.maximum_size = 1536000
board_build.partitions = partitions_singleapp_large.csv
board_build.sdkconfig_defaults = sdkconfig.defaults
monitor_speed = 115200

[env:adafruit_qtpy_esp32c3]
platform = espressif32 @ 6.13.0
board = adafruit_qtpy_esp32c3
framework = espidf
board_build.partitions = partitions_singleapp_large.csv
board_build.sdkconfig_defaults = sdkconfig.defaults
monitor_speed = 115200
